# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Ann Chan
tagline:          Thoughts 
url:              http://getpoole.com
paginate:         1
baseurl:          http://annchanyt.github.io/poole/
author:
  name:          Ann Chan
  url:            https://twitter.com/annchanyt
  email:          annchanyt@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
